//------------------------------------------------------------------------------
// HACK: not auto-generated
//
// in a Shared Project with Xamarin Studio, this file does NOT
// get auto-generated like you'd expect. You MUST keep this file
// manually in-sync wit the AppResources.resx XML.
//------------------------------------------------------------------------------

namespace Sensus
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sensus.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string String2
        {
            get
            {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }

        internal static string Mood1
        {
            get
            {
                return ResourceManager.GetString("Mood1", resourceCulture);
            }
        }

        internal static string Mood2
        {
            get
            {
                return ResourceManager.GetString("Mood2", resourceCulture);
            }
        }

        internal static string Mood3
        {
            get
            {
                return ResourceManager.GetString("Mood3", resourceCulture);
            }
        }

        internal static string Mood4
        {
            get
            {
                return ResourceManager.GetString("Mood4", resourceCulture);
            }
        }

        internal static string Mood5
        {
            get
            {
                return ResourceManager.GetString("Mood5", resourceCulture);
            }
        }


        internal static string test
        {
            get
            {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }

        internal static string physical_amb
        {
            get
            {
                return ResourceManager.GetString("physical_amb", resourceCulture);
            }
        }

        internal static string work_amb
        {
            get
            {
                return ResourceManager.GetString("work_amb", resourceCulture);
            }
        }

        internal static string fritid_amb
        {
            get
            {
                return ResourceManager.GetString("fritid_amb", resourceCulture);
            }
        }

        internal static string sleep_amb
        {
            get
            {
                return ResourceManager.GetString("sleep_amb", resourceCulture);
            }
        }
        internal static string practical_amb
        {
            get
            {
                return ResourceManager.GetString("practical_amb", resourceCulture);
            }
        }
        internal static string social_amb
        {
            get
            {
                return ResourceManager.GetString("social_amb", resourceCulture);
            }
        }

        internal static string healthy_amb
        {
            get
            {
                return ResourceManager.GetString("healthy_amb", resourceCulture);
            }
        }

    }
}
